# Generated by Django 3.0.3 on 2020-04-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Master',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
                ('role_details', models.CharField(max_length=30)),
                ('role_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Accounts',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=80, unique=True)),
                ('pwd_exp_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='first_app.User_Accounts')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('desingnation', models.CharField(max_length=30, null=True)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('user_status', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
                ('expired_date', models.DateTimeField()),
                ('expired_by', models.CharField(max_length=30)),
                ('no_of_expiry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='assigned_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('assignment_status', models.CharField(max_length=10)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Role_Master')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.User_Accounts')),
            ],
        ),
    ]
