# Generated by Django 3.0.3 on 2020-04-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='assigned_role',
            name='assignment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assigned_role',
            name='assignment_status',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='assigned_role',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Role_Master'),
        ),
        migrations.AlterField(
            model_name='assigned_role',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='role_master',
            name='role_status',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='pwd_exp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='first_app.User_Accounts'),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='user_status',
            field=models.CharField(max_length=1),
        ),
    ]
