# Generated by Django 3.0.3 on 2020-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20200420_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='expired_by',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='no_of_expiry',
        ),
        migrations.AlterField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
    ]
