# Generated by Django 3.0.3 on 2020-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20200420_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='expired_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_master',
            name='expired_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_master',
            name='no_of_expiry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
    ]
