# Generated by Django 3.0.3 on 2020-04-20 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20200420_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_role',
            name='role_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.Role_Master'),
        ),
        migrations.AlterField(
            model_name='assigned_role',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='expired_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='no_of_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
