# Generated by Django 3.0.3 on 2020-04-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20200420_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_role',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Role_Master'),
        ),
        migrations.AlterField(
            model_name='assigned_role',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
        migrations.AlterUniqueTogether(
            name='assigned_role',
            unique_together={('user_id', 'role_id')},
        ),
    ]
