# Generated by Django 3.0.3 on 2020-05-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20200504_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
