# Generated by Django 3.0.3 on 2020-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_auto_20200505_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_master',
            name='assigned_users',
            field=models.ManyToManyField(through='first_app.Assigned_Role', to='first_app.User_Master'),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
